name = "Lean Topology game"
version = "1.0.0"
extra_files = "extras"
intro = "src/game/intro.lean"

[[worlds]]
name = "Basic definitions"
id = 1
levels = [
	"src/game/basic_defs_world/level1.lean",
]

[[worlds]]
name = "Interior world"
id = 2
parents = [1]
levels = [
	"src/game/interior_world/level1.lean",
	"src/game/interior_world/level2.lean",
	"src/game/interior_world/level3.lean",
	"src/game/interior_world/level4.lean",
	"src/game/interior_world/level5.lean",
]
