# This is a basic workflow to help you get started with Actions

name: Update Mathlib and build

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 2 * * *' # every day
  # Triggers the workflow on push or pull request events but only for the main and test branch
  push:
    branches: [ main, test ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      production:
        description: 'Deploy to production (default: false). If false, will deploy to test subfolder.'
        required: false
        default: false
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout test branch
        uses: actions/checkout@v2
        if: ${{ !github.event.inputs.production || github.ref_name == 'test' }}
        with:
          ref: test
      
      - name: Checkout main branch
        uses: actions/checkout@v2
        if: ${{ github.event.inputs.production && github.event.ref == 'main' }}
        with:
          ref: main

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Update packages
        run: sudo apt install -y curl
 
      - name: Install elan
        run: |
          set -o pipefail
          curl https://raw.githubusercontent.com/Kha/elan/master/elan-init.sh -sSf | sh -s -- -v -y
          sudo ln -s $HOME/.elan/bin/* /usr/local/bin;

      - name: Install python Lean dependencies
        run: |
          python -m pip install --upgrade pip mathlibtools

      - name: Try to upgrade Lean and dependencies
        run: |
          leanproject up
          leanproject build
